In [1]:
# Creating a matrix as a Python list
matrix_python = [
    [1, 2, 3],
    [4, 5, 6]
]

matrix_python

[[1, 2, 3], [4, 5, 6]]

In [21]:
print(matrix_python[0])
print(matrix_python[1])

[1, 2, 3]
[4, 5, 6]


In [9]:
# Access elements of a python list
element = matrix_python[0][1]
print("The element is:", element)

The element is: 2


In [10]:
len(matrix_python)

2

In [17]:
matrix_python[0]

[1, 2, 3]

In [22]:
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]

print(A)
print(B)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]


In [27]:
print("Rows in A", len(A))
print("Columns in A", A[0])

Rows in A 2
Columns in A [1, 2]


In [28]:
# Matrix multiplication (manual implementation)
def matrix_multiply(A, B):
    # Initialize result matrix with zeros
    rows_A = len(A)
    cols_A = len(A[0])
    cols_B = len(B[0])
    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]
    
    # Perform multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]
                
    return result

In [29]:

# Example usage
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]
result = matrix_multiply(A, B)
print(result)  # [[19, 22], [43, 50]]

[[19, 22], [43, 50]]


Numpy Approach via ndarray (n dimensional array)

In [32]:
!pip install numpy

In [33]:
import numpy as np

# Creating a matrix as a NumPy array
matrix_numpy = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix_numpy)

[[1 2 3]
 [4 5 6]]


In [36]:
# Accessing elements
element = matrix_numpy[0, 1]  # Gets 6 (row 0, column 1)
print(element)


2


In [42]:
# Matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A =", A); print("B", B)

A = [[1 2]
 [3 4]]
B [[5 6]
 [7 8]]


In [43]:
# Matrix multiplication (much simpler than with Python lists)
result1 = np.dot(A, B)  # Using dot product
result2 = A @ B         # Using the @ operator (Python 3.5+)
print(result1)    
print(result2)      


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [45]:

# Other matrix operations
transpose = A.T
print(A)
print(transpose)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [46]:
inverse = np.linalg.inv(A)
print(A)

[[1 2]
 [3 4]]


In [59]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("The Eigen Values \n", eigenvalues)
print("The Eigen Vectors \n", eigenvectors)

The Eigen Values 
 [-0.37228132  5.37228132]
The Eigen Vectors 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [60]:
determinant = np.linalg.det(A)
print(determinant)

-2.0000000000000004


In [61]:
from numpy import linalg as la

In [62]:
eigenvalues, eigenvectors = la.eig(A)
eigenvalues

array([-0.37228132,  5.37228132])

## Tensors

In [64]:
!pip install tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 645.0/645.0 MB 379.7 kB/s eta 0:00:0000:0100:21
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 858.4 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 935.5 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 390.2 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 756.2 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 571.7 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 594.3 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 132.2 kB/s eta 0:00:00a 0:00:03
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 1.0 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 886.9 kB/s eta 0:00:00a 0:00:01
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.4
    Uninstalling numpy-2.2.4:
      Successfull

In [65]:
import tensorflow as tf

# Creating a matrix as a TensorFlow tensor
matrix_tf = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix_tf)

2025-03-23 11:57:24.116487: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-23 11:57:24.120138: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-23 11:57:24.129142: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1742720244.143914   23406 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742720244.150460   23406 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1742720244.161627   23406 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linkin

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


E0000 00:00:1742720248.558075   23406 cuda_executor.cc:1228] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1742720249.185395   23406 gpu_device.cc:2341] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [66]:
print(matrix_tf)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [70]:
# Accessing elements
element = matrix_tf[0, 2]  # Gets 3 (row 0, column 2)

print(element)

tf.Tensor(3, shape=(), dtype=int32)


In [71]:
# Matrix operations with tensors
A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

print(A)
print(B)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [72]:
# Matrix multiplication
result = tf.matmul(A, B)
print(result)  # tf.Tensor([[19. 22.], [43. 50.]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [73]:
# Gradient computation (unique to TensorFlow)
with tf.GradientTape() as tape:
    tape.watch(A)
    C = tf.matmul(A, B)
    loss = tf.reduce_mean(C)

gradient = tape.gradient(loss, A)
print(gradient)  # Shows the gradient of the mean with respect to A

tf.Tensor(
[[2.75 3.75]
 [2.75 3.75]], shape=(2, 2), dtype=float32)


In [74]:
# For machine learning models
x = tf.constant([[1.0, 2.0]])
layer = tf.keras.layers.Dense(3)  # Create a dense layer
layer

<Dense name=dense, built=False>

In [75]:
output = layer(x)  # Apply the layer to input tensor
output

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-1.8607349, -1.0246518,  1.6487751]], dtype=float32)>